"""审查行为配置(.ai-review.yaml)。

与 gateway 配置(模型/key)分离:这里只控制"审什么、多细、发不发"。
参考 .coderabbit.yaml 的哲学:初版先 chill,控制噪音。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

try:  # PyYAML 是 pr-review 唯一新增运行时依赖
    import yaml
except ImportError:  # pragma: no cover - 依赖缺失时给出可读错误
    yaml = None  # type: ignore[assignment]

# 严重级别从高到低
SEVERITIES = ("error", "warn", "info")


@dataclass
class QualityConfig:
    """质量门配置(LLM-as-judge 自检循环, P1b)。

    详设: docs/pr-review-quality-gate.md
    """

    # 一键开关:关闭则完全跳过 judge 打分与重写
    enabled: bool = True
    # judge 用模型(空=与审查同模型; 独立配置时传 model 覆盖)
    judge_model: str = ""
    # 低于该分触发重写; 太高重试爆炸, 太低失去门禁意义
    pass_score: int = 70
    # 重写硬上限, 防死循环; 耗尽后降级(说明评论 + check neutral)
    max_rewrites: int = 3
    # judge 输入预算(大 PR 截断用)
    max_judge_input_chars: int = 8000
    # linter 交叉验证层(首版仅预留, 未实现; 开启需工作流安装对应 linter)
    lint_enabled: bool = False
    lint_only: list[str] = field(default_factory=lambda: ["py", "go", "js"])


@dataclass
class ReviewToolsConfig:
    """agentic 审查工具(仓库代码访问, 形态二, 2026-08-15)。"""

    # 一键开关: 关闭则审查退化为纯 prompt(不注入工具)
    enabled: bool = True
    # 单轮审查最多工具调用次数(硬上限, 防 agent 无限探索)
    max_tool_calls: int = 12
    # 单次工具结果最多字符(防 token 爆炸)
    max_result_chars: int = 6000
    # 单文件最多读多少行(防大文件爆上下文)
    max_file_lines: int = 200


@dataclass
class ReviewConfig:
    # 审查重点(直接作为指令进入 prompt)
    review_focus: list[str] = field(
        default_factory=lambda: [
            "bug 与逻辑错误",
            "并发/性能隐患",
            "安全问题(注入/越权/密钥泄露)",
            "资源泄漏(连接/文件未关闭)",
            "明显不符合项目既有约定(命名/分层/异常处理)",
        ]
    )
    # 忽略的路径(glob, 支持 **)
    ignore_paths: list[str] = field(
        default_factory=lambda: [
            "**/*.lock",
            "**/package-lock.json",
            "**/pnpm-lock.yaml",
            "**/yarn.lock",
            "**/*.min.js",
            "**/*.min.css",
            "**/vendor/**",
            "**/generated/**",
            "**/dist/**",
            "**/build/**",
            "**/target/**",
            "**/.idea/**",
            "**/.vscode/**",
        ]
    )
    # 只发出达到该级别及以上的问题(error > warn > info)
    min_severity: str = "warn"
    # 合并门禁:存在达到该级别及以上的问题时, check-run 失败 + job exit 1(PR 变红)
    #   error: 只有 error 拦(推荐) | warn: warn 也拦 | off: 永不拦(只发评论)
    fail_on_severity: str = "error"
    # 切片:每批最多文件数(大 PR 分批审,控制单次 prompt token)
    max_files_per_batch: int = 20
    # 单文件 patch 超过该行数则截断(在评论中提示)
    max_lines_per_file: int = 800
    # 是否在评论中附带模型/token/成本统计
    show_stats: bool = True
    # 仓库上下文:审查前收集这些文件(glob,相对仓库根)注入 prompt,
    # 让 AI 结合项目约定/API 契约判断(第一轮评估 2/3 误报的根因是缺此上下文)
    context_files: list[str] = field(
        default_factory=lambda: [
            "AGENTS.md",
            "README.md",
            "docs/**/*.md",
            "spec/**",
        ]
    )
    # 上下文注入的总预算(字符),超预算按配置顺序截断
    max_context_chars: int = 8000
    # 生成代码检测:文件头含 Generated by/@generated/DO NOT EDIT 标记的跳过审查
    ignore_generated: bool = True
    # 线程决议驱动(P1a):用户在线程表态(resolve/ignore)后,下轮 review 不再重复报
    resolve_enabled: bool = True
    # 已处理清单注入 prompt 的上限条数(超限截断,防 prompt 膨胀)
    max_handled_lines: int = 200
    # 质量门(P1b):judge 打分 + 自检重写
    quality_gate: QualityConfig = field(default_factory=QualityConfig)
    # 审查调用的 LLM 温度: 审查是判断型任务, 低温度提升稳定性(避免同一 diff 时报时不报);
    # 回复模式(P0)仍用 gateway 默认温度(对话需要一点随机性)
    review_temperature: float = 0.3
    # 审查批次输出预算(token): gateway 默认 max_tokens=1024 太小,
    # 多 issues JSON 会被截断成非法 JSON → 静默空结果事故(2026-08-14 线上 bug)
    review_max_tokens: int = 4096
    # agentic 审查工具(仓库代码访问, 形态二)
    review_tools: ReviewToolsConfig = field(default_factory=ReviewToolsConfig)

    def severity_rank(self, severity: str) -> int:
        s = (severity or "info").strip().lower()
        if s not in SEVERITIES:
            return 0  # 未知级别按最低处理
        return SEVERITIES.index(s)

    def passes_filter(self, severity: str) -> bool:
        """是否达到 min_severity 门槛。"""
        return self.severity_rank(severity) <= self.severity_rank(self.min_severity)

    def should_ignore(self, path: str) -> bool:
        from fnmatch import fnmatch

        p = path.replace("\\", "/")
        for pat in self.ignore_paths:
            if fnmatch(p, pat):
                return True
            # fnmatch 中 "**/" 需要路径含斜杠,补一次根路径匹配:
            # "**/package-lock.json" 也要命中仓库根的 package-lock.json
            if pat.startswith("**/") and fnmatch(p, pat[3:]):
                return True
        return False


DEFAULT_CONFIG = ReviewConfig()


def load_config(path: str | Path | None = None) -> ReviewConfig:
    """加载 .ai-review.yaml;文件缺失/为空时使用默认配置。

    注意:返回全新实例,绝不修改模块级 DEFAULT_CONFIG 单例。
    """
    cfg = ReviewConfig()  # 默认值与 DEFAULT_CONFIG 一致,但独立可变
    if yaml is None:
        return cfg
    if path is None or not Path(path).is_file():
        return cfg

    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    focus = data.get("review_focus")
    if focus:
        cfg.review_focus = list(focus)
    ignore = data.get("ignore_paths")
    if ignore:
        cfg.ignore_paths = list(ignore)
    if data.get("min_severity") in SEVERITIES:
        cfg.min_severity = data["min_severity"]
    if data.get("fail_on_severity") in SEVERITIES + ("off",):
        cfg.fail_on_severity = data["fail_on_severity"]
    cfg.max_files_per_batch = int(data.get("max_files_per_batch", cfg.max_files_per_batch))
    cfg.max_lines_per_file = int(data.get("max_lines_per_file", cfg.max_lines_per_file))
    cfg.show_stats = bool(data.get("show_stats", cfg.show_stats))
    cfg.max_context_chars = int(data.get("max_context_chars", cfg.max_context_chars))
    if data.get("context_files"):
        cfg.context_files = list(data["context_files"])
    if "ignore_generated" in data:
        cfg.ignore_generated = bool(data["ignore_generated"])
    if "resolve_enabled" in data:
        cfg.resolve_enabled = bool(data["resolve_enabled"])
    cfg.max_handled_lines = int(data.get("max_handled_lines", cfg.max_handled_lines))
    if "review_temperature" in data:
        cfg.review_temperature = float(data["review_temperature"])
    if "review_max_tokens" in data:
        cfg.review_max_tokens = int(data["review_max_tokens"])
    # review_tools 块(agentic 仓库访问)
    rt = data.get("review_tools") or {}
    if isinstance(rt, dict):
        if "enabled" in rt:
            cfg.review_tools.enabled = bool(rt["enabled"])
        if "max_tool_calls" in rt:
            cfg.review_tools.max_tool_calls = int(rt["max_tool_calls"])
        if "max_result_chars" in rt:
            cfg.review_tools.max_result_chars = int(rt["max_result_chars"])
        if "max_file_lines" in rt:
            cfg.review_tools.max_file_lines = int(rt["max_file_lines"])
    # quality_gate 块(缺失则用默认; lint 层首版仅预留)
    qg = data.get("quality_gate") or {}
    if isinstance(qg, dict):
        if "enabled" in qg:
            cfg.quality_gate.enabled = bool(qg["enabled"])
        if qg.get("judge_model"):
            cfg.quality_gate.judge_model = str(qg["judge_model"])
        cfg.quality_gate.pass_score = int(qg.get("pass_score", cfg.quality_gate.pass_score))
        cfg.quality_gate.max_rewrites = int(qg.get("max_rewrites", cfg.quality_gate.max_rewrites))
        cfg.quality_gate.max_judge_input_chars = int(
            qg.get("max_judge_input_chars", cfg.quality_gate.max_judge_input_chars)
        )
        if "lint_enabled" in qg:
            cfg.quality_gate.lint_enabled = bool(qg["lint_enabled"])
        if qg.get("lint_only"):
            cfg.quality_gate.lint_only = list(qg["lint_only"])
    return cfg
