"""Prompt 组装:把仓库上下文 + PR 信息 + 文件 diff 变成 LLM 输入。

输出约束:强制 LLM 返回纯 JSON(文件+行号+级别+问题+建议+依据),便于解析与评论。

v2 改进(基于第一轮 review 质量评估, devops-dashboard PR #2):
- 误报 #1/#2 根因是 AI 只看 diff 不看设计意图 → 增加"判断纪律"约束
  (不假设接口参数/状态管理方式, 需结合契约与证据下结论, 不确定的标 needs_review)
- 噪音 #4 根因是审了生成代码 → schema 增加 category, 配合 ignore_generated 过滤
- 显式要求检查"请求模型 vs 响应模型同名字段类型一致性"(该类型问题准确率最高)
"""

from __future__ import annotations

import json
from typing import Any

from .config import ReviewConfig
from .diff import FileDiff
from .github import PRInfo, REVIEW_MARKER

# 回复模式(P0 交互):用户在行内评论线程回复时,AI 在此线程内简洁回答
REPLY_SYSTEM_PROMPT = """你是 PR 审查助手,正在回应开发者对某条审查意见的回复。
要求:
- 回复务必简洁:不超过 3 句话(约 150 字),直接回答,不要复述问题、不要客套
- 只针对开发者的问题/质疑回答:解释判断依据、承认误报、或补充具体修改建议
- 若开发者说明这是设计意图或已解决,表示确认并简短说明,不要强辩、不要重复报
- 纯文本回答,不要输出 JSON 或代码块(除非确实需要一小段代码示意)
"""


def build_reply_messages(thread: list[dict]) -> list[dict[str, str]]:
    """组装回复对话:线程对话历史(旧→新)+ 用户最新回复。

    thread: [{id, body, user:{login}, in_reply_to_id}, ...] 按时间正序。
    """
    parts: list[str] = ["## 线程对话历史(旧→新)"]
    for c in thread:
        body = c.get("body", "")
        if REVIEW_MARKER in body:
            author = "AI 审查"
        else:
            author = (c.get("user") or {}).get("login", "开发者")
        parts.append(f"**{author}**: {body}")
    user_content = "\n\n".join(parts)
    return [
        {"role": "system", "content": REPLY_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

SYSTEM_PROMPT = """你是一位资深代码审查专家,正在审查一个 Pull Request。
你只依据提供的 diff 与仓库上下文给出**真实、具体、可执行**的审查意见,遵循以下规则:

1. 只审查 diff 中改动过的行,不要审查未改动的既有代码。
2. 不要为了凑数而评论:没有真问题就输出空 issues 数组。
3. 每条意见必须包含文件、行号(新文件行号)、严重级别、分类、标题、详细说明、修改建议、判断依据。
4. 行号必须与 diff 中标注的新文件行号一致,无法确定行号时用 0。

【判断纪律】(降低误报的关键,务必遵守)
5. 严重级别只能是 error / warn / info 之一:
   - error: 明确会导致 bug、安全漏洞、数据丢失(必须有代码/契约证据)
   - warn: 潜在问题、明显隐患、违反项目约定
   - info: 建议性改进(可读性、可维护性)
6. 判断"前端 API 调用是否合理"时,必须结合仓库上下文中的后端接口定义/API 契约(spec)判断;
   不要假设接口"需要额外参数",除非契约中有明确证据。
7. 不要假设某个值"应该在表单/state 里"——前端状态管理方式多种多样(useState/表单库/全局store),
   只有看到证据才下结论;React state 通过闭包读取是正常模式。
8. 无法确认设计意图的问题,必须设 needs_review=true(需人工确认),不得当作确定性 bug。
9. 显式检查: 请求 DTO 与响应模型中**同名字段的类型是否一致**(如 authType: string vs 枚举)。
   这类契约一致性问题价值最高,优先找。
10. 安全类建议必须指出正确的落地位置(后端/前端)并考虑威胁模型;
    例如 SSRF 的防御在后端而非前端校验, 前端校验无法防御直接调 API。
11. 每条 issue 必须给出 evidence(判断依据: 引用的 diff 行号/契约字段/代码片段),
    给不出具体依据的问题不要报。
12. 生成代码(文件头含 Generated by / @generated / DO NOT EDIT)不在审查范围,除非有手写逻辑混入。

输出 JSON 结构(严格遵循):
{
  "summary": "对这个 PR 的整体判断,1-2 句话;无论是否发现问题都必须输出——无问题时给出基于 diff 的正面评价(如'改动结构清晰, 未发现明显问题')",
  "issues": [
    {
      "file": "src/foo.py",
      "line": 42,
      "severity": "warn",
      "category": "bug | security | convention | design_intent | resource | type_consistency | other",
      "title": "简短的问题标题",
      "detail": "问题描述,说明为什么是问题",
      "suggestion": "具体的修改建议",
      "evidence": "判断依据:引用的代码/契约位置,如 'spec 中 CreateAgentRequest.authType 为 string, 而 AgentTarget.authType 为枚举'",
      "needs_review": false
    }
  ]
}
"""


def build_messages(
    pr_info: PRInfo,
    files: list[FileDiff],
    config: ReviewConfig,
    batch_no: int | None = None,
    batch_total: int | None = None,
    repo_context: str = "",
    handled: list[tuple[str, int]] | None = None,
    feedback: list[str] | None = None,
) -> list[dict[str, str]]:
    """组装一轮审查的 messages([system, user])。

    repo_context: 仓库约定/契约文档摘要(AGENTS.md/spec 等),注入在 diff 之前,
    帮助 AI 结合项目约定与后端契约判断(第一轮评估中 2/3 误报的根因就是缺此上下文)。
    handled: 已处理清单 [(file, line), ...] — 用户在线程已确认解决/忽略的问题,
    要求 AI 不要重复报(P1a 决议驱动)。
    feedback: judge 的质量反馈(重写轮),要求 AI 修正(P1b 质量门)。
    """
    focus_text = "\n".join(f"- {f}" for f in config.review_focus)
    batch_note = (
        f"\n注意:本次是第 {batch_no}/{batch_total} 批,只给出这批文件的问题。"
        if batch_no and batch_total
        else ""
    )

    parts: list[str] = [
        f"# PR #{pr_info.number}: {pr_info.title}",
        f"分支: {pr_info.head_ref} -> {pr_info.base_ref}",
        f"变更文件数: {len(files)}",
        "",
        "## 审查重点(按重要度排序)",
        focus_text,
        "",
    ]
    if repo_context:
        parts += ["## 仓库上下文(约定/契约,判断依据,请先阅读)", "", repo_context.strip(), ""]
    if handled:
        parts += [
            "## 已处理清单(以下问题已在线程对话中确认解决或属设计意图)",
            "对这些位置不要重复报问题,除非出现了新的、不同的缺陷。",
            "",
        ]
        for path, line in handled:
            parts.append(f"- {path}:{line}")
        parts.append("")
    if feedback:
        parts += ["## 上一轮质量反馈(必须修正的问题)", ""]
        parts.extend(f"- {r}" for r in feedback)
        parts.append("")
    parts += [
        "## 变更内容(diff)",
        "",
    ]
    for fd in files:
        parts.append(f"### 文件: {fd.path} (状态: {fd.status})")
        parts.extend(fd.to_display_lines())
        parts.append("")

    user_content = "\n".join(parts).strip() + batch_note
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def parse_review_json(content: str) -> dict[str, Any]:
    """容错解析 LLM 输出的 JSON。

    LLM 偶尔会加 ```json 围栏或前后多余文本,这里做轻量清理。
    """
    text = content.strip()
    # 去掉 markdown 围栏
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()
    # 截取第一个 { 到最后一个 }(容错额外说明文本)
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"LLM 输出中未找到 JSON 对象: {content[:200]!r}")
    return json.loads(text[start : end + 1])
