"""Prompt 组装:把仓库上下文 + PR 信息 + 文件 diff 变成 LLM 输入。

输出约束:强制 LLM 返回纯 JSON(文件+行号+级别+问题+建议+依据),便于解析与评论。

v2 改进(基于第一轮 review 质量评估, devops-dashboard PR #2):
- 误报 #1/#2 根因是 AI 只看 diff 不看设计意图 → 增加"判断纪律"约束
  (不假设接口参数/状态管理方式, 需结合契约与证据下结论, 不确定的标 needs_review)
- 噪音 #4 根因是审了生成代码 → schema 增加 category, 配合 ignore_generated 过滤
- 显式要求检查"请求模型 vs 响应模型同名字段类型一致性"(该类型问题准确率最高)
"""

from __future__ import annotations

import json
import re
from typing import Any

from .config import ReviewConfig
from .diff import FileDiff
from .github import PRInfo, REVIEW_MARKER

# 回复模式(P0 交互):用户在行内评论线程回复时,AI 在此线程内简洁回答
REPLY_SYSTEM_PROMPT = """你是 PR 审查助手,正在回应开发者对某条审查意见的回复。
要求:
- 回复务必简洁:不超过 3 句话(约 150 字),直接回答,不要复述问题、不要客套
- 只针对开发者的问题/质疑回答:解释判断依据、承认误报、或补充具体修改建议
- 若开发者说明这是设计意图或已解决,表示确认并简短说明,不要强辩、不要重复报
- 纯文本回答,不要输出 JSON 或代码块(除非确实需要一小段代码示意)
"""


def build_reply_messages(thread: list[dict]) -> list[dict[str, str]]:
    """组装回复对话:线程对话历史(旧→新)+ 用户最新回复。

    thread: [{id, body, user:{login}, in_reply_to_id}, ...] 按时间正序。
    """
    parts: list[str] = ["## 线程对话历史(旧→新)"]
    for c in thread:
        body = c.get("body", "")
        if REVIEW_MARKER in body:
            author = "AI 审查"
        else:
            author = (c.get("user") or {}).get("login", "开发者")
        parts.append(f"**{author}**: {body}")
    user_content = "\n\n".join(parts)
    return [
        {"role": "system", "content": REPLY_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

SYSTEM_PROMPT = """你是一位资深代码审查专家,正在审查一个 Pull Request。
你只依据提供的 diff 与仓库上下文给出**真实、具体、可执行**的审查意见,遵循以下规则:

## 审查范围
1. 只审查 diff 中改动过的行,不要审查未改动的既有代码。
2. 不要为了凑数而评论:没有真问题就输出空 issues 数组。
3. 生成代码(文件头含 Generated by / @generated / DO NOT EDIT)不在审查范围,除非有手写逻辑混入。

## 输出格式
4. 每条意见必须包含文件、行号(新文件行号)、严重级别、分类、标题、详细说明、修改建议、
   判断依据(evidence);给不出具体依据的问题不要报。
5. 行号必须与 diff 中标注的新文件行号一致,无法确定行号时用 0。
6. 【一语中的, 杜绝发散】title 精简(≤ 30 字); detail 只说关键证据与后果, 不要长篇大论、
   不要复述 diff、不要给可选的多套方案、不要泛泛谈"建议补充测试"。

## 严重级别(两轴事实判断, 数字由系统映射)
7. 每条 issue 必须给出两个**事实判断**字段(不要直接输出严重级别数字, 系统按规则映射):
   - `trigger`(必然性): `real`(存在真实触发路径, 必然/可直接利用) /
     `hypothetical`("若 X 失败则…"类故障分支, 需特定故障才发生) / `style`(纯风格, 不涉行为)
   - `impact`(后果): `fatal`(数据丢失/崩溃/资金损失/严重越权) /
     `functional`(功能错误/数据不一致/安全风险) / `minor`(可恢复降级/防御性缺失) / `none`(无)
8. 【非原则性不得高判】"若 X 失败则…"这类**假设性故障路径**(操作非原子、清理/降级失败、
   异常分支——没有真实必然触发路径)一律 `trigger=hypothetical`, 即使后果涉及安全/权限/数据
   完整性——系统会映射为较低级别(必修线以下, 仅提醒不强制)。只有存在**真实触发路径**的
   问题才允许 `trigger=real`(可能映射为必修/严重/致命)。确认不了就设 needs_review。

   **并发/竞态类断言尤其容易高判**(本仓实测的高发误报): "两个请求/两个线程可能同时…"
   "若关停发生在构建窗口内…" 这类表述只是**可能性**, 不是事实。判 `trigger=real` 的前提是
   你能指出**具体交错**(谁先谁后、涉及哪个锁/字段)或给出**可复现步骤**——把它写进
   `verification`(如"构造 X 后并发触发 Y, 断言 Z 失败")。给不出具体交错的竞态结论
   一律 `trigger=hypothetical`(不阻塞合并), 并在 `detail` 里说明"属推演"。
   注意: 锁被持有时间过长、串行化性能退化这类**可确定的**问题不受此限, 按实际后果定级。

## 判断纪律(降低误报)
9. 【不要报语言语义已保证安全的行为】语言运行时已保证安全的模式不要报(如 Go 的 range 遍历
   nil/空切片是安全的、判空后 return 是安全的、dict.get 有默认值)。报任何一条前先自问
   "作者能否用一句话反驳", 能反驳就不报; 也不要报自相矛盾的问题(自己承认不违反约定的不要报)。
   **例外(必须报)**: 违反仓库上下文(AGENTS.md 等)中**明确约定**的问题——如"所有返回 error
   的调用必须被处理""禁止硬编码密钥""导出符号必须有注释"。只要 diff 触发了该约定, 就必须报,
   这属于约定违反而非"语言语义安全", 不要因"作者可能反驳"而放弃。
10. 无法确认设计意图的问题, 必须设 needs_review=true(需人工确认),不得当作确定性 bug。
11. 不要假设某个值"应该在表单/state 里"——前端状态管理方式多种多样(useState/表单库/全局store),
    只有看到证据才下结论;React state 通过闭包读取是正常模式。
12. 安全类建议必须指出正确的落地位置(后端/前端)并考虑威胁模型;
    例如 SSRF 的防御在后端而非前端校验, 前端校验无法防御直接调 API。

## 契约一致性(价值最高, 优先找)
13. 显式检查: 请求 DTO 与响应模型中**同名字段的类型是否一致**(如 authType: string vs 枚举)。
14. 判断"前端 API 调用是否合理"时,必须结合仓库上下文中的后端接口定义/API 契约(spec)判断;
    不要假设接口"需要额外参数",除非契约中有明确证据。

## 同根因合并与收敛
15. 【同根因合并, 多位置用 locations】同一根因的多个表现必须合并为一条 issue:
    title 概括根因, detail 说明根因与后果, **locations 列出全部受影响位置**(可跨文件)。
    禁止同一根因在多个调用处/文件各报一条。判断标准: 修复方式相同、证据指向同一
    契约/函数/模式 → 同一根因, 合并。示例: 前后端契约不一致波及 3 个调用处 →
    1 条 issue, locations 列 3 个位置, 而非 3 条。
16. 【审查收敛, 禁止换角度重复报】同一根因的问题已被修复或本轮已报过, 不得换角度/换位置
    再次报出(如先报"策略残留"再报"数据不一致"再报"静默降级", 实为同一根因)。
    后续评审/重写轮只关注**新增的、之前未提过**的问题。判断是否同一根因: 修复方式相同、
    证据指向同一函数/模式 → 同一根因, 已报过就不要再报。

## 仓库代码访问(审查前先评估)
17. 【主动查看相关代码, 有节制】审查每个变更前, 先判断是否需要看 diff 之外的代码, 需要就调用工具
    (read_file / grep / ast_grep / list_dir), 不要臆测未看到的代码:
    - 函数行为变更/新增 → 必须 grep 函数名查调用方, 确认是否破坏既有调用约定
    - 契约字段变更 → 查所有使用处
    - 新类型/新函数 → 查是否已有同名约定
    工具不可用或查不到时, 按现有信息判断即可, 不要因此凑数报问题。
    **节制**: 每次调用前想清楚要查什么; 同类查询连续 2-3 次无新信息就停止探索,
    基于已有信息输出 JSON 结论, 不要无限 grep/read_file。
    **禁止文本工具调用**: 工具调用只能通过结构化 tool_calls 机制完成, 严禁在输出正文中
    写 `<tool_calls>` / `<invoke name="...">` 之类的工具调用文本——那会被当作无效输出;
    想要工具就发结构化 tool_calls, 不想调工具就直接输出 JSON。

18. 【可验证性: 门禁级问题必须能证明】`trigger=real` 且后果非 none 的问题会映射到必修及以上,
    必须填写 `verification`, 说明**怎么证明这条结论**, 三选一:
    ① 复现路径(具体输入/命令/请求); ② 与之矛盾的现有测试名(并说明该测试为何挡不住);
    ③ `none: 属推演`——即你自己也承认拿不出验证路径。系统会确定性处理第 ③ 种:
    门禁级问题标为推演会被降级到提醒级, 不会阻塞合并。**宁可标 ③ 也不要编造验证路径**;
    同时, 凡是能用一句"作者可这样反驳"挡回去的问题, 按规则 9 直接不要报。

19. 【语言语义不得凭直觉断言】user 消息里会给出「技术栈与语言语义边界」。任何主张"这段代码
    违反语言/框架语义"的问题(异常处理、真值判断、异步生命周期、数据类校验、类型), 必须在
    `verification` 里引用具体规则, 或给出可复现片段(如 `python -c "print(bool({'a': []}))"`)。
    凭 Java/JS 等其它语言的直觉推断"应该是这样"不算依据——这类问题会被确定性降级到提醒级。

20. 【机器已确认的维度不要重复报】user 消息里会列出"已由机器确认通过"的维度(如类型检查 mypy、
    测试 pytest、风格 ruff)。若仍要报这些维度的问题, **必须填写 `tool_gap` 字段**说明该工具
    为什么没拦住它(如: 该文件不在工具检查范围、这条 check 未配置/已改名、该规则工具未覆盖)。
    `tool_gap` 留空会被确定性降级到提醒级——**不要**把解释写在 detail/evidence 里当替代,
    系统只认这个字段(这样才不会把"类型标注缺失"之类的普通描述误当成解释)。
    注意: 纯风格/约定问题(convention)本身不计入阻塞门禁。

输出 JSON 结构(严格遵循):
{
  "summary": "对这个 PR 的整体判断,1-2 句话。无论是否发现问题都必须输出——无问题时给出基于 diff 的正面评价(如'改动结构清晰, 未发现明显问题')。有问题时概括改动质量与主要风险方向(如'结构清晰,但存在一个安全类问题需关注'),不要复述具体 issue 内容——具体问题在下方 issues 列表详述",
  "issues": [
    {
      "file": "src/foo.py",        // 主位置(必填)
      "line": 42,                  // 主位置行号
      "locations": [{"file": "src/bar.py", "line": 10}],  // 同根因的其他位置(可选, 合并时列出全部)
      "trigger": "real | hypothetical | style",   // 事实判断1: 必然性(见规则7)
      "impact": "fatal | functional | minor | none",  // 事实判断2: 后果(见规则7)
      "category": "bug | security | convention | design_intent | resource | type_consistency | other",
      "title": "简短的问题标题",
      "detail": "问题描述,说明为什么是问题",
      "suggestion": "具体的修改建议;能给出修复代码时,用 Markdown 代码块给出可直接参考的修复代码(如完整函数或关键片段,标注文件与改动点)",
      "evidence": "判断依据:引用的代码/契约位置,如 'spec 中 CreateAgentRequest.authType 为 string, 而 AgentTarget.authType 为枚举'",
      "verification": "可验证路径(必修及以上必须给): 三选一 —— 复现输入/命令(如 'POST /api/x 传 tenant_id=\"abc\" 返回 500'); 或能反驳本结论的现有测试名(并说明它为何挡不住); 或 \"none: 属推演\"",
      "tool_gap": "仅当本问题落在'已由机器确认通过'的维度上(如类型检查/风格检查)时需要: 说明该工具为什么没拦住它(如该文件不在检查范围/该 check 未配置/规则未覆盖); 其他情况留空",
      "needs_review": false
    }
  ]
}
"""


def build_stack_block(stack: Any, verified: list[dict[str, str]] | None = None) -> str:
    """P0-4/P0-5: 组装「技术栈与语义边界」块(注入 user message, 不进 system 常量)。

    stack: StackConfig(语言/框架/异步运行时/仓库备注)
    verified: 已由机器确认通过的维度 [{"dimension", "tool", "name", "conclusion"}] —
              来自 CI check-run 的真实结果, 不是模型猜测(报告 P0-5 要求注入"真实结果")。
    """
    languages = list(getattr(stack, "languages", []) or [])
    semantics = stack.semantics() if hasattr(stack, "semantics") else []
    notes = list(getattr(stack, "notes", []) or [])
    verified = verified or []
    if not (languages or semantics or notes or verified):
        return ""

    lines: list[str] = ["## 技术栈与语言语义边界(P0-4/P0-5)"]
    head = []
    if languages:
        head.append("语言: " + ", ".join(languages))
    if getattr(stack, "framework", ""):
        head.append("框架: " + str(stack.framework))
    if getattr(stack, "async_runtime", ""):
        head.append("异步运行时: " + str(stack.async_runtime))
    if head:
        lines.append("- " + "; ".join(head))
    if semantics:
        lines += [
            "",
            "审查时必须遵守下列语言语义(左侧直觉来自其它语言, 右侧是本项目的真实规则; "
            "违反它们的「看起来像 bug」的结论属误报):",
        ]
        lines += [f"- {x}" for x in semantics]
    if notes:
        lines += ["", "仓库特有的语义提醒:", *[f"- {x}" for x in notes]]
    if verified:
        dims = "、".join(
            f"{v.get('dimension', '?')}(由 {v.get('tool') or v.get('name') or '工具'} 负责)"
            for v in verified
        )
        lines += [
            "",
            f"已由机器确认通过的维度: {dims}。",
            "这些维度上的问题应由上述工具回答, 不要在审查里重复报; 确有必要报时必须说明"
            "「为什么现有工具没拦住」(见规则 20)。",
        ]
    return "\n".join(lines)


def build_messages(
    pr_info: PRInfo,
    files: list[FileDiff],
    config: ReviewConfig,
    batch_no: int | None = None,
    batch_total: int | None = None,
    repo_context: str = "",
    handled: list[tuple[str, int]] | None = None,
    feedback: list[str] | None = None,
    stack_block: str = "",
) -> list[dict[str, str]]:
    """组装一轮审查的 messages([system, user])。

    repo_context: 仓库约定/契约文档摘要(AGENTS.md/spec 等),注入在 diff 之前,
    帮助 AI 结合项目约定与后端契约判断(第一轮评估中 2/3 误报的根因就是缺此上下文)。
    handled: 已处理清单 [(file, line), ...] — 用户在线程已确认解决/忽略的问题,
    要求 AI 不要重复报(P1a 决议驱动)。
    feedback: judge 的质量反馈(重写轮),要求 AI 修正(P1b 质量门)。
    """
    focus_text = "\n".join(f"- {f}" for f in config.review_focus)
    batch_note = (
        f"\n注意:本次是第 {batch_no}/{batch_total} 批,只给出这批文件的问题。"
        if batch_no and batch_total
        else ""
    )

    parts: list[str] = [
        f"# PR #{pr_info.number}: {pr_info.title}",
        f"分支: {pr_info.head_ref} -> {pr_info.base_ref}",
        f"变更文件数: {len(files)}",
        "",
        "## 审查重点(按重要度排序)",
        focus_text,
        "",
    ]
    if stack_block:
        parts += [stack_block.strip(), ""]
    if repo_context:
        parts += ["## 仓库上下文(约定/契约,判断依据,请先阅读)", "", repo_context.strip(), ""]
    if handled:
        parts += [
            "## 已处理清单(以下问题已在线程对话中确认解决或属设计意图)",
            "对这些位置不要重复报问题,除非出现了新的、不同的缺陷。",
            "",
        ]
        for path, line in handled:
            parts.append(f"- {path}:{line}")
        parts.append("")
    if feedback:
        parts += ["## 上一轮质量反馈(必须修正的问题)", ""]
        parts.extend(f"- {r}" for r in feedback)
        parts.append("")
    parts += [
        "## 变更内容(diff)",
        "",
    ]
    for fd in files:
        parts.append(f"### 文件: {fd.path} (状态: {fd.status})")
        parts.extend(fd.to_display_lines())
        parts.append("")

    user_content = "\n".join(parts).strip() + batch_note
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def parse_review_json(content: str) -> dict[str, Any]:
    """容错解析 LLM 输出的 JSON。

    LLM 偶尔会加 ```json 围栏、前后多余文本、单引号或未加引号的 key
    (工具历史消息变长后格式漂移更频繁),这里做多级容错。
    """
    text = content.strip()
    # 1. 去掉 markdown 围栏
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()
    # 2. 截取第一个 { 到最后一个 }(容错额外说明文本)
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"LLM 输出中未找到 JSON 对象: {content[:200]!r}")
    raw = text[start : end + 1]
    try:
        return json.loads(raw)
    except ValueError:
        # 3. 修复非严格 JSON(无引号 key / 单引号字符串)再解析
        repaired = _repair_json(raw)
        try:
            return json.loads(repaired)
        except ValueError as e:
            raise ValueError(f"LLM 输出非法 JSON(修复后仍失败): {e}: {raw[:200]!r}") from e


# 无引号 key: {summary: ...} / ,issues: [...](修复为 "summary": ...)
_JSON_KEY_RE = re.compile(r"([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*:)")
# 成对单引号字符串(保守: 内部反斜杠转义参与匹配)
_JSON_SINGLE_QUOTE_RE = re.compile(r"'((?:[^'\\]|\\.)*)'")


def _repair_json(raw: str) -> str:
    """LLM 非严格 JSON 修复: 无引号 key 补引号 + 单引号字符串转双引号。

    仅在严格 json.loads 失败后作为兜底; 修复后仍失败则由调用方抛错。
    """
    s = _JSON_KEY_RE.sub(r'\1"\2"\3', raw)
    s = _JSON_SINGLE_QUOTE_RE.sub(r'"\1"', s)
    return s
