"""审查编排:取 PR 文件 → 过滤/切片 → 调 LLM → 解析 → 发评论。

与 CodeRabbit 的差异:初版发整体 review 评论(JSON 结构含文件+行号),
行内评论作为后续增强,post_review 已预留 comments 参数。
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from gateway import ChatResponse, LLMClient

from .config import ReviewConfig
from .diff import DiffHunk, FileDiff, parse_diff
from .github import GitHubClient, PRInfo
from .prompt import build_messages, parse_review_json
from .reply import RESOLUTION_MARK_RE

logger = logging.getLogger("pr_review")

SEVERITY_ICONS = {"error": "🔴", "warn": "🟡", "info": "🔵"}

# 生成代码识别标记(文件头命中任一即视为生成代码,跳过审查)
_GENERATED_MARKERS = (
    "generated by",
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
)


@dataclass
class ReviewIssue:
    file: str
    line: int
    severity: str
    title: str
    detail: str
    suggestion: str
    category: str = "other"  # bug / security / convention / design_intent / resource / type_consistency / other
    evidence: str = ""       # 判断依据(引用代码/契约位置)
    needs_review: bool = False  # 需人工确认(设计意图类不确定判断,不计入门禁)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ReviewIssue":
        return cls(
            file=str(d.get("file", "")),
            line=int(d.get("line", 0) or 0),
            severity=str(d.get("severity", "info")).lower(),
            title=str(d.get("title", "")),
            detail=str(d.get("detail", "")),
            suggestion=str(d.get("suggestion", "")),
            category=str(d.get("category", "other")),
            evidence=str(d.get("evidence", "")),
            needs_review=bool(d.get("needs_review", False)),
        )


@dataclass
class ReviewResult:
    """一轮(或一批)审查的结果汇总。"""

    batches: int = 0
    issues: list[ReviewIssue] = field(default_factory=list)
    summaries: list[str] = field(default_factory=list)
    total_cost: float = 0.0
    total_tokens: int = 0
    model: str = ""
    skipped_files: int = 0
    # 本次是第几次评审(1 起),0 表示未知(不显示)
    review_no: int = 0
    # 文件 -> 新增行号集合(用于行内评论定位校验, GitHub 要求 line 必须是被修改的行)
    added_lines: dict[str, set[int]] = field(default_factory=dict)
    # 质量门(P1b)结果
    quality_score: float | None = None
    quality_verdict: str | None = None  # pass / rewrite / degraded
    quality_reasons: list[str] = field(default_factory=list)
    rewrites: int = 0
    # 审查输出 JSON 解析失败的批次(2026-08-14 事故后引入: 失败必须显式, 不能静默变空 issues)
    parse_errors: list[str] = field(default_factory=list)

    @property
    def has_issues(self) -> bool:
        return bool(self.issues)

    @property
    def severity_counts(self) -> dict[str, int]:
        """各严重级别问题数量,供 check-run 门禁判定。"""
        counts: dict[str, int] = {"error": 0, "warn": 0, "info": 0}
        for issue in self.issues:
            counts[issue.severity] = counts.get(issue.severity, 0) + 1
        return counts


class ReviewRunner:
    """pr-review 主流程。按批次切片,每批独立走 LLM,最后汇总发一条评论。"""

    def __init__(
        self,
        github: GitHubClient,
        llm: LLMClient,
        config: ReviewConfig,
        *,
        max_retry_bad_json: int = 1,
        repo_root: str | Path | None = None,
        context: str = "",
    ):
        self.github = github
        self.llm = llm
        self.config = config
        self.max_retry_bad_json = max_retry_bad_json
        # 仓库根(action 环境=checkout 目录),用于生成代码文件头检测;None 表示不读文件
        self.repo_root = Path(repo_root) if repo_root else None
        # 仓库上下文(约定/契约文档摘要),注入 prompt 降低设计意图类误报
        self.context = context

    # ------------------------------------------------------------------ 入口
    def run(self) -> ReviewResult:
        pr = self.github.get_pr_info()
        raw_files = self.github.get_pr_files()

        candidates: list[FileDiff] = []
        skipped = 0
        for item in raw_files:
            path = item.get("filename", "")
            if self.config.should_ignore(path):
                skipped += 1
                continue
            if self._is_generated_file(path):
                skipped += 1
                continue
            # 没有 patch 的(超大文件/二进制)跳过
            patch = item.get("patch", "")
            if not patch:
                skipped += 1
                continue
            # 解析 patch(支持完整 diff 与 GitHub API 裸 hunk 两种格式)
            parsed = parse_diff(patch)
            if not parsed or not parsed[0].hunks:
                # 解析不出变更行(格式异常),跳过,避免把"空 diff"喂给 LLM
                skipped += 1
                continue
            candidates.append(
                FileDiff(
                    path=path,
                    old_path=item.get("previous_filename", ""),
                    status=item.get("status", "modified"),
                    hunks=parsed[0].hunks,
                )
            )

        # 单文件超长:截断 hunk 行,避免单次 prompt 爆 token
        for fd in candidates:
            self._truncate_if_too_long(fd)

        if not candidates:
            logger.info("没有可审查的文件(全部被忽略或无 diff)")
            return ReviewResult(skipped_files=skipped)

        result = ReviewResult(model=self.llm.config.get().model, skipped_files=skipped)
        # 记录每个文件的新增行号集合,供行内评论定位校验
        for fd in candidates:
            result.added_lines[fd.path] = {line_no for line_no, _ in fd.added}
        batches = self._batch_files(candidates)
        result.batches = len(batches)
        self._last_candidates = candidates  # 供质量门 judge 核对 diff

        # P1a 决议驱动:扫描线程,提取用户已确认解决/忽略的位置,不再重复报
        handled = self._collect_handled()
        if handled:
            logger.info("已处理清单 %d 条(线程决议),注入 prompt 并过滤", len(handled))

        # 批次审查(P1b 重写轮复用)
        result = self._run_batches(pr, batches, result, handled=handled)

        # P1b 质量门:judge 打分,不达标带反馈整批重审
        if self.config.quality_gate.enabled:
            result = self._quality_loop(pr, batches, result, handled=handled)

        # 排序: severity 降序(error > warn > info)优先, 同级别按 file+line
        priority = {"error": 2, "warn": 1, "info": 0}
        result.issues.sort(
            key=lambda i: (-priority.get(i.severity, 0), i.file, i.line)
        )
        return result

    # ------------------------------------------------------------------ 批次执行
    def _run_batches(
        self,
        pr: PRInfo,
        batches: list[list[FileDiff]],
        result: ReviewResult,
        *,
        handled: list[tuple[str, int]] | None = None,
        feedback: list[str] | None = None,
    ) -> ReviewResult:
        """执行全部批次,汇总到 result(重写轮带 feedback 注入)。"""
        for idx, batch in enumerate(batches, start=1):
            try:
                resp = self._review_batch(pr, batch, idx, len(batches), handled=handled, feedback=feedback)
            except ValueError as e:
                # 重试耗尽仍非法: 显式标记, 不静默降级成空 issues(2026-08-14 事故修复)
                result.parse_errors.append(str(e))
                logger.error("批次 %d 审查输出非法 JSON(重试耗尽): %s", idx, e)
                continue
            summary = self._extract_summary(resp.content)
            if summary:  # 过滤空 summary,避免评论里出现空 bullet
                result.summaries.append(summary)
            result.issues.extend(self._extract_issues(resp.content, handled=handled))
            result.total_cost += resp.cost
            result.total_tokens += resp.prompt_tokens + resp.completion_tokens
        return result

    # ------------------------------------------------------------------ 质量门循环
    def _quality_loop(
        self,
        pr: PRInfo,
        batches: list[list[FileDiff]],
        result: ReviewResult,
        *,
        handled: list[tuple[str, int]] | None = None,
    ) -> ReviewResult:
        """judge 打分 → 不达标带 reasons 整批重审(Reflexion 式) → 耗尽降级。

        重写轮 issues 不叠加,以最后一轮为准。

        空 issues 短路(线上 bug 修复): 审查正确输出空 issues 时——
        - diff 无代码变更(纯文档/配置 PR)→ 跳过质量门直接 pass, 不浪费 token
        - diff 有代码变更 → 只做一次漏报检查(重写上限 1), 防止 judge 误判引发大循环

        解析失败短路(2026-08-14 事故): 任一批次 JSON 解析失败 → 跳过质量门
        (不评估"失败产物", 防 judge 把空 issues 误判为 pass), 直接 degraded。
        """
        from .quality import Judge

        if result.parse_errors:
            result.quality_verdict = "degraded"
            logger.error(
                "审查输出解析失败 %d 个批次, 跳过质量门: %s",
                len(result.parse_errors), result.parse_errors[0][:200],
            )
            return result

        judge = Judge(llm=self.llm, config=self.config.quality_gate)
        diff_text = self._diff_text()

        if not result.issues:
            if not self._has_code_changes():
                result.quality_verdict = "pass"
                result.quality_score = float(self.config.quality_gate.pass_score)
                logger.info("无代码变更且无 issues, 跳过质量门")
                return result
            logger.info("有代码变更但无 issues, 仅做一次漏报检查")
        max_rewrites = (
            1 if not result.issues else self.config.quality_gate.max_rewrites
        )

        for attempt in range(max_rewrites + 1):
            jr = judge.evaluate(result, diff_text)
            result.quality_score = jr.score
            result.quality_reasons = jr.reasons
            if jr.verdict == "pass":
                result.quality_verdict = "pass"
                logger.info("质量门通过: %s 分(第 %d 轮)", jr.score, attempt + 1)
                break
            result.quality_verdict = "rewrite"
            if attempt >= max_rewrites:
                result.quality_verdict = "degraded"
                logger.warning(
                    "质量门降级: 重写 %d 次仍低于阈值(%s 分 < %s)",
                    result.rewrites, jr.score, self.config.quality_gate.pass_score,
                )
                break
            # 带 judge reasons 整批重审; 新结果替换旧 issues(不叠加)
            result.rewrites += 1
            logger.info(
                "质量门重写 %d/%d: %s 分, feedback %d 条",
                result.rewrites, max_rewrites, jr.score, len(jr.reasons),
            )
            fresh = ReviewResult(
                model=result.model,
                skipped_files=result.skipped_files,
                added_lines=result.added_lines,
                batches=result.batches,
                rewrites=result.rewrites,  # 保留重写计数
            )
            result = self._run_batches(pr, batches, fresh, handled=handled, feedback=jr.reasons)
        return result

    def _diff_text(self) -> str:
        """全部候选文件的紧凑 diff 文本(judge 核对准确性用)。"""
        parts: list[str] = []
        for fd in getattr(self, "_last_candidates", []):
            parts.append(f"### {fd.path} ({fd.status})")
            parts.extend(fd.to_display_lines())
        return "\n".join(parts)

    # 视为"代码变更"的扩展名(质量门空 issues 短路判断用)
    _CODE_EXTS = {
        ".go", ".py", ".ts", ".tsx", ".js", ".jsx", ".java", ".rs", ".c",
        ".cpp", ".cc", ".kt", ".rb", ".php", ".sh", ".sql", ".vue", ".cs",
    }

    def _has_code_changes(self) -> bool:
        """候选文件里是否存在代码文件(区别于文档/配置/生成内容)。"""
        for fd in getattr(self, "_last_candidates", []):
            if Path(fd.path).suffix.lower() in self._CODE_EXTS:
                return True
        return False

    # ------------------------------------------------------------------ 已处理清单(决议驱动)
    def _collect_handled(self) -> list[tuple[str, int]]:
        """扫描 PR 线程,提取决议标记(<!-- pr-review:resolve|ignore:path:line -->)。

        仅当 config.resolve_enabled 开启;结果按 max_handled_lines 截断。
        """
        if not self.config.resolve_enabled:
            return []
        handled: list[tuple[str, int]] = []
        try:
            comments = self.github.get_pull_comments()
        except Exception as e:  # 网络/权限异常不阻塞主流程
            logger.warning("扫描线程失败(决议驱动降级为不启用): %s", e)
            return []
        for c in comments:
            m = re.search(RESOLUTION_MARK_RE, c.get("body", ""))
            if m:
                handled.append((m.group(2), int(m.group(3))))
        return handled[: self.config.max_handled_lines]

    # ------------------------------------------------------------------ 单批审查
    def _review_batch(
        self,
        pr: PRInfo,
        batch: list[FileDiff],
        batch_no: int,
        batch_total: int,
        handled: list[tuple[str, int]] | None = None,
        feedback: list[str] | None = None,
    ) -> ChatResponse:
        """调 LLM 审查一批, 显式预检 JSON 合法性; 非法则重试, 耗尽抛 ValueError。

        注意: LLMClient.chat 只返回文本不解析 JSON, 这里预检让重试真正生效
        (旧实现等 chat 抛 ValueError 是死代码, 2026-08-14 事故根因之一)。
        """
        messages = build_messages(
            pr, batch, self.config, batch_no, batch_total,
            repo_context=self.context, handled=handled, feedback=feedback,
        )
        last_err: Exception | None = None
        for attempt in range(self.max_retry_bad_json + 1):
            resp = self.llm.chat(
                messages,
                temperature=self.config.review_temperature,
                max_tokens=self.config.review_max_tokens,
            )
            try:
                parse_review_json(resp.content)  # 预检: JSON 合法才收
                return resp
            except ValueError as e:
                last_err = e
                logger.warning("LLM 输出非 JSON(第 %d 次, 共 %d): %s", attempt + 1, self.max_retry_bad_json + 1, e)
        raise ValueError(f"LLM 多次返回非法 JSON,放弃: {last_err}")

    def _extract_summary(self, content: str) -> str:
        """从 JSON 中提取整体判断(失败时返回空串,不把原始 JSON 贴进评论)。"""
        try:
            data = parse_review_json(content)
            return str(data.get("summary", "")).strip()
        except ValueError:
            return ""

    def _extract_issues(
        self, content: str, handled: list[tuple[str, int]] | None = None
    ) -> list[ReviewIssue]:
        try:
            data = parse_review_json(content)
        except ValueError as e:
            logger.warning("解析审查结果失败: %s", e)
            return []
        issues: list[ReviewIssue] = []
        for item in data.get("issues", []) or []:
            issue = ReviewIssue.from_dict(item)
            if not issue.title or not issue.file:
                continue  # 缺关键字段的直接丢弃
            if not self.config.passes_filter(issue.severity):
                continue
            # 决议驱动兜底:命中已处理清单的位置直接过滤(即使 LLM 没遵守 prompt)
            if handled and (issue.file, issue.line) in set(handled):
                logger.info("过滤已处理问题: %s:%s", issue.file, issue.line)
                continue
            issues.append(issue)
        return issues

    # ------------------------------------------------------------------ 切片
    def _batch_files(self, files: list[FileDiff]) -> list[list[FileDiff]]:
        n = self.config.max_files_per_batch
        return [files[i : i + n] for i in range(0, len(files), n)]

    @staticmethod
    def _truncate_if_too_long(fd: FileDiff, max_lines: int = 800) -> None:
        """hunk 行数超过上限时截断保留前半段(保留下一条注释说明)。"""
        total = sum(len(h.lines) for h in fd.hunks)
        if total <= max_lines:
            return
        kept, budget = [], max_lines
        for hunk in fd.hunks:
            if budget <= 0:
                break
            take = min(len(hunk.lines), budget)
            kept.append(DiffHunk(old_start=hunk.old_start, new_start=hunk.new_start, lines=hunk.lines[:take]))
            budget -= take
        kept[-1].lines.append(f"// ... 文件过大,共 {total} 行 diff,仅展示前 {max_lines} 行")
        fd.hunks = kept

    # ------------------------------------------------------------------ 生成代码检测
    def _is_generated_file(self, path: str) -> bool:
        """文件头含生成代码标记(orval/OpenAPI 等)则跳过(噪音 #4 的修复)。

        需仓库根(action 环境有 checkout);本地测试 repo_root=None 时跳过检测。
        """
        if not self.config.ignore_generated or self.repo_root is None:
            return False
        p = Path(self.repo_root) / path
        if not p.is_file():
            return False
        try:
            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                head = "".join(f.readlines()[:5]).lower()
        except OSError:
            return False
        return any(marker in head for marker in _GENERATED_MARKERS)

    # ------------------------------------------------------------------ 行内评论线程
    def build_inline_comments(self, result: ReviewResult) -> list[dict]:
        """生成行内评论线程(GitHub review comments,每条挂在 diff 行上可回复讨论)。

        设计: 整体评论(summary + 问题索引) + 每条可定位问题一个行内线程, 线程里给
        完整修改建议——开发者可在该行直接回复/AI 继续讨论。

        GitHub API 约束: side=RIGHT 时 line 必须是该文件 diff 中的新增行, 否则 422。
        行号不在新增行集合内(如 LLM 给的是上下文行)的 issue 降级: 只留在整体评论。
        """
        comments: list[dict] = []
        for issue in result.issues:
            if not issue.file or not issue.line:
                continue  # 无行号:留整体评论
            added = result.added_lines.get(issue.file)
            if added is None or issue.line not in added:
                continue  # 行号非新增行:留整体评论(避免 422)
            comments.append(
                {
                    "path": issue.file,
                    "line": issue.line,
                    "side": "RIGHT",
                    "body": self._inline_body(issue),
                }
            )
        return comments

    @staticmethod
    def _inline_body(issue: ReviewIssue) -> str:
        """行内评论正文:标题 + 详情 + 建议 + 依据,紧凑格式。"""
        icon = SEVERITY_ICONS.get(issue.severity, "🔵")
        parts = [f"{icon} **{issue.title}**"]
        if issue.needs_review:
            parts.append("> ⚠️ 需人工确认(设计意图类判断)")
        if issue.detail:
            parts.append(issue.detail)
        if issue.suggestion:
            parts.append(f"💡 {issue.suggestion}")
        if issue.evidence:
            parts.append(f"📎 依据: {issue.evidence}")
        return "\n\n".join(parts)

    # ------------------------------------------------------------------ 评论生成
    def format_comment(self, result: ReviewResult) -> str:
        """把审查结果渲染成 PR 评论 Markdown。"""
        header = "## 🤖 AI 代码审查"
        if result.review_no:
            header += f" · 第 {result.review_no} 次评审"
        lines: list[str] = [
            header,
            "",
        ]
        if result.summaries:
            lines.append("**整体判断**:")
            for s in result.summaries:
                lines.append(f"- {s.strip()}")
            lines.append("")

        by_severity: dict[str, list[ReviewIssue]] = {}
        for issue in result.issues:
            by_severity.setdefault(issue.severity, []).append(issue)

        for sev in ("error", "warn", "info"):
            items = by_severity.get(sev, [])
            if not items:
                continue
            lines.append(f"### {SEVERITY_ICONS[sev]} {sev.capitalize()} ({len(items)})")
            for idx, i in enumerate(items, start=1):
                loc = f"`{i.file}`:{i.line}" if i.line else f"`{i.file}`"
                title = f"{i.title} ⚠️" if i.needs_review else i.title
                lines.append(f"{idx}. **{loc}** — {title}")
                if i.needs_review:
                    lines.append("   - ⚠️ 需人工确认(设计意图类判断)")
                if i.detail:
                    lines.append(f"   - {i.detail}")
                if i.suggestion:
                    lines.append(f"   - 💡 {i.suggestion}")
                if i.evidence:
                    lines.append(f"   - 📎 依据: {i.evidence}")
            lines.append("")

        if not result.issues:
            # 无问题时: 优先展示 LLM 的正向评价(如有), 固定提示作结尾
            if not result.summaries:
                lines.append("**整体判断**:")
                lines.append("- 未发现达到审查门槛的问题,改动整体质量良好 ✅")
                lines.append("")
            lines.append("✅ 未发现达到审查门槛的问题")
            lines.append("")

        stats = [
            f"模型: {result.model or '-'}",
            f"批次数: {result.batches}",
            f"token: {result.total_tokens}",
        ]
        if result.total_cost:
            stats.append(f"成本: ¥{result.total_cost:.4f}")
        if result.skipped_files:
            stats.append(f"跳过文件: {result.skipped_files}")
        if self.config.show_stats:
            lines.append("---")
            lines.append("_自动生成 · " + " · ".join(stats) + "_")

        # 机器可读锚点(HTML 注释, 人类不可见): 供 golden 驱动器可靠解析,
        # 解耦 parser 与正文 Markdown 格式(改正文格式不影响解析)。
        meta = {
            "version": 1,
            "issues": [
                {
                    "file": i.file,
                    "line": i.line,
                    "severity": i.severity,
                    "category": i.category,
                    "title": i.title,
                }
                for i in result.issues
            ],
        }
        lines += ["", "<!--AI-REVIEW-META", json.dumps(meta, ensure_ascii=False), "-->"]

        return "\n".join(lines)

    # ------------------------------------------------------------------ 质量门降级评论
    def format_degraded_comment(self, result: ReviewResult) -> str:
        """质量门降级:不发低质量审查,发说明评论(附最后一次 issues 摘要供参考)。"""
        header = "## 🤖 AI 代码审查"
        if result.review_no:
            header += f" · 第 {result.review_no} 次评审"
        lines = [
            header,
            "",
            "⚠️ **本轮 AI 审查质量评估未达标**(多次重写后仍低于阈值)。",
        ]
        if result.quality_score is not None:
            lines.append(
                f"最后一次评分: **{result.quality_score:.0f}/100**(阈值 {self.config.quality_gate.pass_score})"
            )
        lines.append("")
        if result.quality_reasons:
            lines.append("**judge 反馈**:")
            lines.extend(f"- {r}" for r in result.quality_reasons)
            lines.append("")
        lines.append("建议: 稍后手动 rerun 本 workflow, 或进行人工 review。")
        if result.issues:
            lines.append("")
            lines.append("最后一次审出的问题(供参考,未通过质量门):")
            for issue in result.issues:
                loc = f"`{issue.file}`:{issue.line}" if issue.line else f"`{issue.file}`"
                lines.append(f"- {loc} — {issue.title}")
        lines.append("")
        stats = [f"批次数: {result.batches}", f"token: {result.total_tokens}"]
        if result.total_cost:
            stats.append(f"成本: ¥{result.total_cost:.4f}")
        if self.config.show_stats:
            lines.append("---")
            lines.append("_自动生成 · " + " · ".join(stats) + "_")
        return "\n".join(lines)

    def format_parse_failed_comment(self, result: ReviewResult) -> str:
        """审查输出解析失败(2026-08-14 事故修复):发说明评论,告知用户审查未完成。"""
        header = "## 🤖 AI 代码审查"
        if result.review_no:
            header += f" · 第 {result.review_no} 次评审"
        lines = [
            header,
            "",
            "⚠️ **本轮 AI 审查输出解析失败,未能完成审查**(已跳过质量门,不阻塞合并)。",
            "",
            "失败批次:",
        ]
        for e in result.parse_errors[:3]:
            lines.append(f"- `{str(e)[:180]}`")
        if len(result.parse_errors) > 3:
            lines.append(f"- ... 共 {len(result.parse_errors)} 个批次解析失败")
        lines += [
            "",
            "可能原因: 模型输出被截断(超出输出预算)或格式异常, 重试后仍失败。",
            "建议: 稍后手动 rerun 本 workflow, 或进行人工 review。",
        ]
        return "\n".join(lines)
