"""审查编排:取 PR 文件 → 过滤/切片 → 调 LLM → 解析 → 发评论。

与 CodeRabbit 的差异:初版发整体 review 评论(JSON 结构含文件+行号),
行内评论作为后续增强,post_review 已预留 comments 参数。
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from gateway import ChatResponse, LLMClient

from .config import ReviewConfig
from .diff import DiffHunk, FileDiff, parse_diff
from .github import GitHubClient, PRInfo
from .prompt import build_messages, parse_review_json

logger = logging.getLogger("pr_review")

SEVERITY_ICONS = {"error": "🔴", "warn": "🟡", "info": "🔵"}

# 生成代码识别标记(文件头命中任一即视为生成代码,跳过审查)
_GENERATED_MARKERS = (
    "generated by",
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
)


@dataclass
class ReviewIssue:
    file: str
    line: int
    severity: str
    title: str
    detail: str
    suggestion: str
    category: str = "other"  # type_consistency / security / design_intent / resource / convention / other
    evidence: str = ""       # 判断依据(引用代码/契约位置)
    needs_review: bool = False  # 需人工确认(设计意图类不确定判断,不计入门禁)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ReviewIssue":
        return cls(
            file=str(d.get("file", "")),
            line=int(d.get("line", 0) or 0),
            severity=str(d.get("severity", "info")).lower(),
            title=str(d.get("title", "")),
            detail=str(d.get("detail", "")),
            suggestion=str(d.get("suggestion", "")),
            category=str(d.get("category", "other")),
            evidence=str(d.get("evidence", "")),
            needs_review=bool(d.get("needs_review", False)),
        )


@dataclass
class ReviewResult:
    """一轮(或一批)审查的结果汇总。"""

    batches: int = 0
    issues: list[ReviewIssue] = field(default_factory=list)
    summaries: list[str] = field(default_factory=list)
    total_cost: float = 0.0
    total_tokens: int = 0
    model: str = ""
    skipped_files: int = 0
    # 本次是第几次评审(1 起),0 表示未知(不显示)
    review_no: int = 0
    # 文件 -> 新增行号集合(用于行内评论定位校验, GitHub 要求 line 必须是被修改的行)
    added_lines: dict[str, set[int]] = field(default_factory=dict)

    @property
    def has_issues(self) -> bool:
        return bool(self.issues)

    @property
    def severity_counts(self) -> dict[str, int]:
        """各严重级别问题数量,供 check-run 门禁判定。"""
        counts: dict[str, int] = {"error": 0, "warn": 0, "info": 0}
        for issue in self.issues:
            counts[issue.severity] = counts.get(issue.severity, 0) + 1
        return counts


class ReviewRunner:
    """pr-review 主流程。按批次切片,每批独立走 LLM,最后汇总发一条评论。"""

    def __init__(
        self,
        github: GitHubClient,
        llm: LLMClient,
        config: ReviewConfig,
        *,
        max_retry_bad_json: int = 1,
        repo_root: str | Path | None = None,
        context: str = "",
    ):
        self.github = github
        self.llm = llm
        self.config = config
        self.max_retry_bad_json = max_retry_bad_json
        # 仓库根(action 环境=checkout 目录),用于生成代码文件头检测;None 表示不读文件
        self.repo_root = Path(repo_root) if repo_root else None
        # 仓库上下文(约定/契约文档摘要),注入 prompt 降低设计意图类误报
        self.context = context

    # ------------------------------------------------------------------ 入口
    def run(self) -> ReviewResult:
        pr = self.github.get_pr_info()
        raw_files = self.github.get_pr_files()

        candidates: list[FileDiff] = []
        skipped = 0
        for item in raw_files:
            path = item.get("filename", "")
            if self.config.should_ignore(path):
                skipped += 1
                continue
            if self._is_generated_file(path):
                skipped += 1
                continue
            # 没有 patch 的(超大文件/二进制)跳过
            patch = item.get("patch", "")
            if not patch:
                skipped += 1
                continue
            # 解析 patch(支持完整 diff 与 GitHub API 裸 hunk 两种格式)
            parsed = parse_diff(patch)
            if not parsed or not parsed[0].hunks:
                # 解析不出变更行(格式异常),跳过,避免把"空 diff"喂给 LLM
                skipped += 1
                continue
            candidates.append(
                FileDiff(
                    path=path,
                    old_path=item.get("previous_filename", ""),
                    status=item.get("status", "modified"),
                    hunks=parsed[0].hunks,
                )
            )

        # 单文件超长:截断 hunk 行,避免单次 prompt 爆 token
        for fd in candidates:
            self._truncate_if_too_long(fd)

        if not candidates:
            logger.info("没有可审查的文件(全部被忽略或无 diff)")
            return ReviewResult(skipped_files=skipped)

        result = ReviewResult(model=self.llm.config.get().model, skipped_files=skipped)
        # 记录每个文件的新增行号集合,供行内评论定位校验
        for fd in candidates:
            result.added_lines[fd.path] = {line_no for line_no, _ in fd.added}
        batches = self._batch_files(candidates)
        result.batches = len(batches)

        for idx, batch in enumerate(batches, start=1):
            resp = self._review_batch(pr, batch, idx, len(batches))
            result.summaries.append(self._extract_summary(resp.content))
            result.issues.extend(self._extract_issues(resp.content))
            result.total_cost += resp.cost
            result.total_tokens += resp.prompt_tokens + resp.completion_tokens

        result.issues.sort(key=lambda i: (i.file, i.line))
        return result

    # ------------------------------------------------------------------ 单批审查
    def _review_batch(
        self, pr: PRInfo, batch: list[FileDiff], batch_no: int, batch_total: int
    ) -> ChatResponse:
        messages = build_messages(
            pr, batch, self.config, batch_no, batch_total, repo_context=self.context
        )
        last_err: Exception | None = None
        for _ in range(self.max_retry_bad_json + 1):
            try:
                return self.llm.chat(messages)
            except ValueError as e:  # JSON 解析失败:重试一次
                last_err = e
                logger.warning("LLM 输出非 JSON,重试: %s", e)
        raise RuntimeError(f"LLM 多次返回非法 JSON,放弃: {last_err}")

    def _extract_summary(self, content: str) -> str:
        """从 JSON 中提取整体判断(失败时返回空串,不把原始 JSON 贴进评论)。"""
        try:
            data = parse_review_json(content)
            return str(data.get("summary", "")).strip()
        except ValueError:
            return ""

    def _extract_issues(self, content: str) -> list[ReviewIssue]:
        try:
            data = parse_review_json(content)
        except ValueError as e:
            logger.warning("解析审查结果失败: %s", e)
            return []
        issues: list[ReviewIssue] = []
        for item in data.get("issues", []) or []:
            issue = ReviewIssue.from_dict(item)
            if not issue.title or not issue.file:
                continue  # 缺关键字段的直接丢弃
            if not self.config.passes_filter(issue.severity):
                continue
            issues.append(issue)
        return issues

    # ------------------------------------------------------------------ 切片
    def _batch_files(self, files: list[FileDiff]) -> list[list[FileDiff]]:
        n = self.config.max_files_per_batch
        return [files[i : i + n] for i in range(0, len(files), n)]

    @staticmethod
    def _truncate_if_too_long(fd: FileDiff, max_lines: int = 800) -> None:
        """hunk 行数超过上限时截断保留前半段(保留下一条注释说明)。"""
        total = sum(len(h.lines) for h in fd.hunks)
        if total <= max_lines:
            return
        kept, budget = [], max_lines
        for hunk in fd.hunks:
            if budget <= 0:
                break
            take = min(len(hunk.lines), budget)
            kept.append(DiffHunk(old_start=hunk.old_start, new_start=hunk.new_start, lines=hunk.lines[:take]))
            budget -= take
        kept[-1].lines.append(f"// ... 文件过大,共 {total} 行 diff,仅展示前 {max_lines} 行")
        fd.hunks = kept

    # ------------------------------------------------------------------ 生成代码检测
    def _is_generated_file(self, path: str) -> bool:
        """文件头含生成代码标记(orval/OpenAPI 等)则跳过(噪音 #4 的修复)。

        需仓库根(action 环境有 checkout);本地测试 repo_root=None 时跳过检测。
        """
        if not self.config.ignore_generated or self.repo_root is None:
            return False
        p = Path(self.repo_root) / path
        if not p.is_file():
            return False
        try:
            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                head = "".join(f.readlines()[:5]).lower()
        except OSError:
            return False
        return any(marker in head for marker in _GENERATED_MARKERS)

    # ------------------------------------------------------------------ 行内评论线程
    def build_inline_comments(self, result: ReviewResult) -> list[dict]:
        """生成行内评论线程(GitHub review comments,每条挂在 diff 行上可回复讨论)。

        设计: 整体评论(summary + 问题索引) + 每条可定位问题一个行内线程, 线程里给
        完整修改建议——开发者可在该行直接回复/AI 继续讨论。

        GitHub API 约束: side=RIGHT 时 line 必须是该文件 diff 中的新增行, 否则 422。
        行号不在新增行集合内(如 LLM 给的是上下文行)的 issue 降级: 只留在整体评论。
        """
        comments: list[dict] = []
        for issue in result.issues:
            if not issue.file or not issue.line:
                continue  # 无行号:留整体评论
            added = result.added_lines.get(issue.file)
            if added is None or issue.line not in added:
                continue  # 行号非新增行:留整体评论(避免 422)
            comments.append(
                {
                    "path": issue.file,
                    "line": issue.line,
                    "side": "RIGHT",
                    "body": self._inline_body(issue),
                }
            )
        return comments

    @staticmethod
    def _inline_body(issue: ReviewIssue) -> str:
        """行内评论正文:标题 + 详情 + 建议 + 依据,紧凑格式。"""
        icon = SEVERITY_ICONS.get(issue.severity, "🔵")
        parts = [f"{icon} **{issue.title}**"]
        if issue.needs_review:
            parts.append("> ⚠️ 需人工确认(设计意图类判断)")
        if issue.detail:
            parts.append(issue.detail)
        if issue.suggestion:
            parts.append(f"💡 {issue.suggestion}")
        if issue.evidence:
            parts.append(f"📎 依据: {issue.evidence}")
        return "\n\n".join(parts)

    # ------------------------------------------------------------------ 评论生成
    def format_comment(self, result: ReviewResult) -> str:
        """把审查结果渲染成 PR 评论 Markdown。"""
        header = "## 🤖 AI 代码审查"
        if result.review_no:
            header += f" · 第 {result.review_no} 次评审"
        lines: list[str] = [
            header,
            "",
        ]
        if result.summaries:
            lines.append("**整体判断**:")
            for s in result.summaries:
                lines.append(f"- {s.strip()}")
            lines.append("")

        by_severity: dict[str, list[ReviewIssue]] = {}
        for issue in result.issues:
            by_severity.setdefault(issue.severity, []).append(issue)

        for sev in ("error", "warn", "info"):
            items = by_severity.get(sev, [])
            if not items:
                continue
            lines.append(f"### {SEVERITY_ICONS[sev]} {sev.capitalize()} ({len(items)})")
            for i in items:
                loc = f"`{i.file}`:{i.line}" if i.line else f"`{i.file}`"
                title = f"{i.title} ⚠️" if i.needs_review else i.title
                lines.append(f"- **{loc}** — {title}")
                if i.needs_review:
                    lines.append("  - ⚠️ 需人工确认(设计意图类判断)")
                if i.detail:
                    lines.append(f"  - {i.detail}")
                if i.suggestion:
                    lines.append(f"  - 💡 {i.suggestion}")
                if i.evidence:
                    lines.append(f"  - 📎 依据: {i.evidence}")
            lines.append("")

        if not result.issues:
            lines.append("未发现达到审查门槛的问题 ✅")
            lines.append("")

        stats = [
            f"模型: {result.model or '-'}",
            f"批次数: {result.batches}",
            f"token: {result.total_tokens}",
        ]
        if result.total_cost:
            stats.append(f"成本: ¥{result.total_cost:.4f}")
        if result.skipped_files:
            stats.append(f"跳过文件: {result.skipped_files}")
        if self.config.show_stats:
            lines.append("---")
            lines.append("_自动生成 · " + " · ".join(stats) + "_")
        return "\n".join(lines)
